name: Build

on:
  push:
  pull_request:

jobs:
  build:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          # native stable
          - name: "stable linux"
            os: "ubuntu-latest"
            target: "x86_64-unknown-linux-gnu"
            rust_version: "stable"
          - name: "stable mac"
            os: "macos-latest"
            target: "x86_64-apple-darwin"
            rust_version: "stable"
          - name: "stable windows"
            os: "windows-latest"
            target: "x86_64-pc-windows-msvc"
            rust_version: "stable"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          target: ${{ matrix.target }}
          profile: minimal
          components: clippy
          default: true

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --target ${{ matrix.target }} --examples --tests -- -D warnings

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples --tests --target ${{ matrix.target }}

      - name: doc
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -D warnings
        with:
          command: doc
          args: --no-deps --target ${{ matrix.target }}

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          default: true

      - name: check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: check denies
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          log-level: warn
          command: check
          arguments: --all-features
