name: Build

on:
  push:
  pull_request:

env:
  CI_RUST_VERSION: "1.94"
  CI_RUST_MSRV: "1.92"
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  build:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          # native stable
          - name: "stable linux"
            os: "ubuntu-latest"
          - name: "stable mac"
            os: "macos-latest"
          - name: "stable windows"
            os: "windows-latest"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_VERSION }}
          components: clippy

      - uses: taiki-e/install-action@cargo-nextest

      - uses: Swatinem/rust-cache@v2

      - name: check
        run: cargo clippy --all-targets

      - name: doc
        run: cargo doc --no-deps

      - name: test
        run: cargo nextest run --no-tests=pass

      - name: doctest
        run: cargo test --doc

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_VERSION }}
          components: rustfmt

      - name: check format
        run: cargo fmt --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: check denies
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          log-level: warn
          command: check
          arguments: --all-features

  msrv:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: ""
      RUSTDOCFLAGS: ""
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - uses: cwfitzgerald/repo-common/.github/actions/install-rust@trunk
        with:
          version: ${{ env.CI_RUST_MSRV }}

      - uses: Swatinem/rust-cache@v2

      - name: check
        run: cargo check

      - name: check (no default features)
        run: cargo check --no-default-features
